### ISSUE TITLE
使用resnet训练时遇到加载数据遇到问题

### ISSUE THREAD

**Issue by LXLun** [Sanster/tf_crnn#8]
WARNING:tensorflow:From /home/luoxilun/ocr/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py:417: calling reverse_sequence (from tensorflow.python.ops.array_ops) with seq_dim is deprecated and will be removed in a future version.
Instructions for updating:
seq_dim is deprecated, use seq_axis instead
WARNING:tensorflow:From /home/luoxilun/ocr/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py:432: calling reverse_sequence (from tensorflow.python.ops.array_ops) with batch_dim is deprecated and will be removed in a future version.
Instructions for updating:
batch_dim is deprecated, use batch_axis instead
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main()
  File "train.py", line 193, in main
    trainer = Trainer(args)
  File "train.py", line 49, in __init__
    self.model = CRNN(self.cfg, num_classes=self.converter.num_classes)
  File "/home/luoxilun/tf_crnn/nets/crnn.py", line 29, in __init__
    self._build_train_op()
  File "/home/luoxilun/tf_crnn/nets/crnn.py", line 95, in _build_train_op
    self.regularization_loss = tf.add_n(tf.losses.get_regularization_losses())
  File "/home/luoxilun/ocr/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2114, in add_n
    raise ValueError("inputs must be a list of at least one Tensor with the "
ValueError: inputs must be a list of at least one Tensor with the same dtype and shape

**Comment by rechardchen123** [comment]
> WARNING:tensorflow:From /home/luoxilun/ocr/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py:417: calling reverse_sequence (from tensorflow.python.ops.array_ops) with seq_dim is deprecated and will be removed in a future version.
> Instructions for updating:
> seq_dim is deprecated, use seq_axis instead
> WARNING:tensorflow:From /home/luoxilun/ocr/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py:432: calling reverse_sequence (from tensorflow.python.ops.array_ops) with batch_dim is deprecated and will be removed in a future version.
> Instructions for updating:
> batch_dim is deprecated, use batch_axis instead
> Traceback (most recent call last):
> File "train.py", line 198, in 
> main()
> File "train.py", line 193, in main
> trainer = Trainer(args)
> File "train.py", line 49, in **init**
> self.model = CRNN(self.cfg, num_classes=self.converter.num_classes)
> File "/home/luoxilun/tf_crnn/nets/crnn.py", line 29, in **init**
> self._build_train_op()
> File "/home/luoxilun/tf_crnn/nets/crnn.py", line 95, in _build_train_op
> self.regularization_loss = tf.add_n(tf.losses.get_regularization_losses())
> File "/home/luoxilun/ocr/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2114, in add_n
> raise ValueError("inputs must be a list of at least one Tensor with the "
> ValueError: inputs must be a list of at least one Tensor with the same dtype and shape

I have met the same problem. Have you solved the problem.
